package mx.edu.cicese.alejandro.voicehelper;

import android.animation.ObjectAnimator;
import android.app.Activity;
import android.content.Context;
import android.media.AudioManager;
import android.os.AsyncTask;
import android.os.Bundle;
import android.os.PowerManager;
import android.util.Log;
import android.view.View;
import android.view.ViewGroup;
import android.view.animation.DecelerateInterpolator;
import android.widget.AdapterView;
import android.widget.ProgressBar;
import android.widget.TextView;

import com.google.android.glass.app.Card;
import com.google.android.glass.media.Sounds;
import com.google.android.glass.widget.CardBuilder;
import com.google.android.glass.widget.CardScrollAdapter;
import com.google.android.glass.widget.CardScrollView;

import java.util.ArrayList;
import java.util.List;

import de.greenrobot.event.EventBus;
import mx.edu.cicese.alejandro.audio.record.AudioClipListener;
import mx.edu.cicese.alejandro.audio.record.OneDetectorManyObservers;

/**
 * An {@link Activity} showing a tuggable "Hello World!" card.
 * <p/>
 * The main content view is composed of a one-card {@link CardScrollView} that provides tugging
 * feedback to the user when swipe gestures are detected.
 * If your Glassware intends to intercept swipe gestures, you should set the content view directly
 * and use a {@link com.google.android.glass.touchpad.GestureDetector}.
 *
 * @see <a href="https://developers.google.com/glass/develop/gdk/touch">GDK Developer Guide</a>
 */
public class MainActivity extends Activity {

    /**
     * {@link CardScrollView} to use as the main content view.
     */
    private CardScrollView mCardScroller;

    private static final String TAG = "VoiceTracker";
    private static final int TAKE_PICTURE_REQUEST = 1;
    private RecordAudioTask recordAudioTask;
    private Context context;
    private String log = "0";
    private ProgressBar progressBar;
    private ObjectAnimator animation;

    /**
     * "Hello World!" {@link View} generated by {@link #buildView()}.
     */
    private View voiceView;
    private View fluencyView;

    @Override
    protected void onCreate(Bundle bundle) {
        super.onCreate(bundle);

        EventBus.getDefault().register(this);
        context = this.getApplicationContext();
        startTask(createAudioLogger(), "Voice Tracker");

        voiceView = buildView(1);
        fluencyView = buildView(2);

        mCardScroller = new CardScrollView(this);
        MyCardScrollAdapter mAdapter = new MyCardScrollAdapter();
        mAdapter.addView(voiceView);
        mAdapter.addView(fluencyView);
        mCardScroller.setAdapter(mAdapter);
        // Handle the TAP event.
        mCardScroller.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                // Plays disallowed sound to indicate that TAP actions are not supported.
                AudioManager am = (AudioManager) getSystemService(Context.AUDIO_SERVICE);
                am.playSoundEffect(Sounds.DISALLOWED);
            }
        });
        setContentView(mCardScroller);
    }

    @Override
    protected void onResume() {
        super.onResume();
        mCardScroller.activate();
    }

    @Override
    protected void onPause() {
        mCardScroller.deactivate();
        super.onPause();
    }

    /**
     * Builds a Glass styled "Hello World!" view using the {@link CardBuilder} class.
     */
    private View buildView(int value) {
        View view = null;
        switch (value){
            case 1:
                view = new CardBuilder(this, CardBuilder.Layout.EMBED_INSIDE)
                        .setEmbeddedLayout(R.layout.activity_main)
                        .setFootnote("Check your volume")
                        .setTimestamp("CICESE")
                        .getView();

                progressBar = (ProgressBar) view.findViewById(R.id.progressBar);
                break;
            case 2:
                view = new CardBuilder(this, CardBuilder.Layout.EMBED_INSIDE)
                        .setEmbeddedLayout(R.layout.activity_fluency)
                        .setFootnote("Check your fluency")
                        .setTimestamp("CICESE")
                        .getView();
                break;
            default:
                view = new CardBuilder(this, CardBuilder.Layout.EMBED_INSIDE)
                        .setEmbeddedLayout(R.layout.activity_main)
                        .setFootnote("Foods you tracked")
                        .setTimestamp("CICESE")
                        .getView();
                break;

        }
        return view;
    }


    @Override
    protected void onStart() {
        super.onStart();
    }


    @Override
    protected void onDestroy() {
        stopAll();
        EventBus.getDefault().unregister(this);
        super.onDestroy();
    }

    private void startTask(AudioClipListener detector, String name) {
        stopAll();

        recordAudioTask = new RecordAudioTask(MainActivity.this, name);
        List<AudioClipListener> observers = new ArrayList<>();
        observers.add(new AudioClipLogWrapper(this));
        //observers.add(new AudioClipLogFixedWrapper(this));
        OneDetectorManyObservers wrapped =
                new OneDetectorManyObservers(detector, observers);
        recordAudioTask.execute(wrapped);
    }

    private void stopAll() {
        Log.d(TAG, "stop record audio");
        shutDownTaskIfNecessary(recordAudioTask);
    }

    private void shutDownTaskIfNecessary(final AsyncTask task) {
        if ((task != null) && (!task.isCancelled())) {
            if ((task.getStatus().equals(AsyncTask.Status.RUNNING))
                    || (task.getStatus()
                    .equals(AsyncTask.Status.PENDING))) {
                Log.d(TAG, "CANCEL " + task.getClass().getSimpleName());
                task.cancel(true);
            } else {
                Log.d(TAG, "task not running");
            }
        }
    }

    /*
    TODO Esto se puede cambiar
     */
    private AudioClipListener createAudioLogger() {
        AudioClipListener audioLogger = new AudioClipListener() {
            @Override
            public boolean heard(short[] audioData, int sampleRate) {
                if (audioData == null || audioData.length == 0) {
                    return true;
                }

                // returning false means the recording won't be stopped
                // users have to manually stop it via the stop button
                return false;
            }
        };

        return audioLogger;
    }

    public void turnOnScreen() {
        PowerManager powerManager = (PowerManager) this.getSystemService(Context.POWER_SERVICE);
        PowerManager.WakeLock wakeLock = powerManager.newWakeLock(PowerManager.ACQUIRE_CAUSES_WAKEUP | PowerManager.FULL_WAKE_LOCK, "Wake Lock");
        if (powerManager.isScreenOn() == false) {
            wakeLock.acquire();
        }
        if (wakeLock.isHeld()) {
            wakeLock.release();
        }
    }

    public void onEventMainThread(AudioClipLogWrapper event) {
        animation = ObjectAnimator.ofInt(progressBar, "progress", (int) event.getCurrentVolume());
        animation.setDuration(200); // 0.5 second
        animation.setInterpolator(new DecelerateInterpolator());
        animation.start();

        voiceView = new CardBuilder(this, CardBuilder.Layout.EMBED_INSIDE)
                .setEmbeddedLayout(R.layout.activity_main)
                .setFootnote("Check your volume")
                .setTimestamp(event.toString())
                .getView();
    }
    /*
    *** TODO Buscar un mejor lugar para esto
    private void takePicture() {
        Intent intent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
        startActivityForResult(intent, TAKE_PICTURE_REQUEST);
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        if (requestCode == TAKE_PICTURE_REQUEST && resultCode == RESULT_OK) {
            String thumbnailPath = data.getStringExtra(Intents.EXTRA_THUMBNAIL_FILE_PATH);
            String picturePath = data.getStringExtra(Intents.EXTRA_PICTURE_FILE_PATH);

            processPictureWhenReady(picturePath);
            // TODO: Show the thumbnail to the user while the full picture is being
            // processed.
        }

        super.onActivityResult(requestCode, resultCode, data);
    }

    private void processPictureWhenReady(final String picturePath) {
        final File pictureFile = new File(picturePath);

        if (pictureFile.exists()) {
            // The picture is ready; process it.
        } else {
            // The file does not exist yet. Before starting the file observer, you
            // can update your UI to let the user know that the application is
            // waiting for the picture (for example, by displaying the thumbnail
            // image and a progress indicator).

            final File parentDirectory = pictureFile.getParentFile();
            FileObserver observer = new FileObserver(parentDirectory.getPath(),
                    FileObserver.CLOSE_WRITE | FileObserver.MOVED_TO) {
                // Protect against additional pending events after CLOSE_WRITE
                // or MOVED_TO is handled.
                private boolean isFileWritten;

                @Override
                public void onEvent(int event, String path) {
                    if (!isFileWritten) {
                        // For safety, make sure that the file that was created in
                        // the directory is actually the one that we're expecting.
                        File affectedFile = new File(parentDirectory, path);
                        isFileWritten = affectedFile.equals(pictureFile);

                        if (isFileWritten) {
                            stopWatching();

                            // Now that the file is ready, recursively call
                            // processPictureWhenReady again (on the UI thread).
                            runOnUiThread(new Runnable() {
                                @Override
                                public void run() {
                                    processPictureWhenReady(picturePath);
                                }
                            });
                        }
                    }
                }
            };
            observer.startWatching();
        }
    }
    */

}
